// <auto-generated />
namespace ConsoleApp5_NetFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedbunchofrelationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedbunchofrelationships));
        
        string IMigrationMetadata.Id
        {
            get { return "202109251038359_added bunch of relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
