// <auto-generated />
namespace ASPNET_MVC_Framework_EntityCRUD_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedReminderTasksforReactsample : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedReminderTasksforReactsample));
        
        string IMigrationMetadata.Id
        {
            get { return "202109301100333_added ReminderTasks for React sample"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
